# [[project]]
# name = ""
# desc = ""
# tags = ["", ""]
# links = [
#   { name = "", url = "" },
#   { name = "", url = "" },
# ]

[[project]]
name = "Demographic trends and the future of growth (EBRD Transition Report 2025-26, Chapter 1)"
desc = "Quantifying the effects of demographic change on economic growth and evaluating which policy levers can realistically offset it (w/ Federica Coelli and Emily Nilsson)"
tags = []
pdf_url = "https://www.ebrd.com/home/news-and-events/publications/economics/transition-reports/transition-report-2025-26/chapters.html#1"
links = [
   { name = "FT", url = "https://www.ft.com/content/3a675f7f-ff46-4b8d-9744-08dfed18d23a" },
   { name = "WSJ", url = "https://www.wsj.com/economy/global/parts-of-europe-at-risk-of-downward-spiral-if-older-voters-stymie-reforms-ebrd-warns-6947369f" }
]

[[project]]
name = "The political economy of demographic change (EBRD Transition Report 2025-26, Chapter 4)"
desc = "Analysing how shifting age structures influence voters' attitudes and the political feasibility of responding to demographic pressures (w/ Zsoka Koczan, Alexander Plekhanov, Zhaosheng Li and Daniel Treisman)"
tags = []
pdf_url = "https://www.ebrd.com/home/news-and-events/publications/economics/transition-reports/transition-report-2025-26/chapters.html#4"
links = [
   { name = "WSJ", url = "https://www.wsj.com/economy/global/parts-of-europe-at-risk-of-downward-spiral-if-older-voters-stymie-reforms-ebrd-warns-6947369f" }
]

[[project]]
name = "Life in Transition Survey IV: Household resilience in a turbulent world"
desc = "Analytical chapters on intergenerational mobility, support for the green transition and job market informality using data from the latest wave of the EBRD-World Bank Life in Transition Survey (w/ Zsoka Koczan)"
tags = []
pdf_url = "https://www.ebrd.com/life-in-transition-iv.pdf"
links = [
   { name = "VoxEU", url = "https://cepr.org/voxeu/columns/social-mobility-and-digital-divides-emerging-economies-evidence-4th-wave-life" },
   { name = "Frankfurter Allgemeine", url = "https://www.faz.net/aktuell/wirtschaft/mehr-wirtschaft/warum-es-kindern-in-osteuropa-schlechter-geht-als-ihren-eltern-trotz-aufschwung-110110899.html" }
]

[[project]]
name = "Promoting structural change (EBRD Transition Report 2024-25, Chapter 2)"
desc = "Structural transformation and (services) export-led growth (w/ Anton Grahed, Helena Schweiger, and Beata Javorcik)"
tags = []
pdf_url = "https://www.ebrd.com/publications/transition-report-202425-promoting-structural-change"
links = [
   { name = "VoxEU", url = "https://cepr.org/voxeu/columns/rise-services-exports-new-pathways-growth" },
]

# [[project]]
# name = "Place-based industrial policies (EBRD Transition Report 2024-25, Chapter 3)"
# desc = "Regional inequality and urban-rural disparities in the EBRD regions (w/ Cevat Aksoy, Francesco Loiacono, Ege Ondes, and Xuanyi Wang)"
# tags = []
# pdf_url = "https://www.ebrd.com/publications/transition-report-202425-regional-inequality-and-special-economic-zones"
# links = [
#    { name = "VoxEU", url = "https://cepr.org/voxeu/columns/special-economic-zones-and-slow-path-regional-convergence" },
# ]

[[project]]
name = "Gender gaps in the labor market impact of the COVID-19 pandemic"
desc = "Policy brief exploring the impact of the Covid-19 pandemic on gender gaps in labor market outcomes (w/ Claudia Hupkau)"
tags = []
pdf_url = "https://www.esade.edu/ecpol/en/publications/las-brechas-de-genero-en-el-mercado-laboral-durante-la-pandemia/"
links = [
  # { name = "", url = "" },
]